-- Script d'insertion des données pour TPINormand
-- Généré automatiquement

USE TPINormand;

-- =====================
-- SecteurActivite
-- =====================
SET IDENTITY_INSERT SecteurActivite ON;
INSERT INTO SecteurActivite (Id, Nom, Description) VALUES (1, N'Vente en boutique', N'Commerces physiques avec caisse et gestion de stock');
INSERT INTO SecteurActivite (Id, Nom, Description) VALUES (2, N'Grande distribution & Retail', N'Supermarchés, chaînes et franchises en vente au détail B2C');
INSERT INTO SecteurActivite (Id, Nom, Description) VALUES (3, N'Négoce & Grossiste', N'Vente en gros B2B, gestion de volumes et livraisons aux revendeurs');
INSERT INTO SecteurActivite (Id, Nom, Description) VALUES (4, N'Fabrication industrielle', N'Usines et ateliers de production manufacturière');
INSERT INTO SecteurActivite (Id, Nom, Description) VALUES (5, N'Artisanat & Ateliers', N'Petites productions manuelles, SAV et réparation');
INSERT INTO SecteurActivite (Id, Nom, Description) VALUES (6, N'Restauration', N'Restaurants, cafés et food trucks');
INSERT INTO SecteurActivite (Id, Nom, Description) VALUES (7, N'Hôtellerie & Catering', N'Hôtels, hébergements et services traiteur');
INSERT INTO SecteurActivite (Id, Nom, Description) VALUES (8, N'Immobilier', N'Agences, courtiers et intermédiaires dans la transaction immobilière');
INSERT INTO SecteurActivite (Id, Nom, Description) VALUES (9, N'Gestion locative', N'Suivi de patrimoine et baux locatifs');
INSERT INTO SecteurActivite (Id, Nom, Description) VALUES (10, N'Logistique & Entrepôt', N'Gestion de stock, picking et expédition');
INSERT INTO SecteurActivite (Id, Nom, Description) VALUES (11, N'Transport & Livraison', N'Gestion de flotte et tournées de livraison');
INSERT INTO SecteurActivite (Id, Nom, Description) VALUES (12, N'Informatique & IT', N'Développement logiciel et support technique');
INSERT INTO SecteurActivite (Id, Nom, Description) VALUES (13, N'Intégration ERP', N'Implémentation et paramétrage de solutions ERP');
INSERT INTO SecteurActivite (Id, Nom, Description) VALUES (14, N'Médical & Paramédical', N'Cabinets, cliniques, pharmacies et professions de santé');
INSERT INTO SecteurActivite (Id, Nom, Description) VALUES (15, N'Bâtiment & Travaux', N'Chantiers, gros œuvre et second œuvre');
INSERT INTO SecteurActivite (Id, Nom, Description) VALUES (16, N'Ingénierie & Bureau d''études', N'Conception technique et projets d''ingénierie');
INSERT INTO SecteurActivite (Id, Nom, Description) VALUES (17, N'Finance & Comptabilité', N'Banques, analystes financiers et contrôle de gestion');
INSERT INTO SecteurActivite (Id, Nom, Description) VALUES (18, N'Holding & Capital', N'Gestion de participations et dividendes');
INSERT INTO SecteurActivite (Id, Nom, Description) VALUES (19, N'Conseil & Coaching', N'Prestations intellectuelles, accompagnement et agences RH');
INSERT INTO SecteurActivite (Id, Nom, Description) VALUES (20, N'E-commerce', N'Vente en ligne et marketplaces');
INSERT INTO SecteurActivite (Id, Nom, Description) VALUES (21, N'Événementiel', N'Organisation d''événements et salons');
INSERT INTO SecteurActivite (Id, Nom, Description) VALUES (22, N'Agriculture & Viticulture', N'Exploitations agricoles, vignobles et maraîchage');
INSERT INTO SecteurActivite (Id, Nom, Description) VALUES (23, N'Éducation & Formation', N'Écoles, centres de formation et universités');
INSERT INTO SecteurActivite (Id, Nom, Description) VALUES (24, N'Association & ONG', N'Organisations à but non lucratif et fondations');
INSERT INTO SecteurActivite (Id, Nom, Description) VALUES (25, N'Médias & Communication', N'Agences de communication, presse et production');
INSERT INTO SecteurActivite (Id, Nom, Description) VALUES (26, N'Juridique & Fiduciaire', N'Études d''avocats, notaires et fiduciaires');
SET IDENTITY_INSERT SecteurActivite OFF;

-- =====================
-- ApplicationOdoo
-- =====================
SET IDENTITY_INSERT ApplicationOdoo ON;
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (1, N'Discussion', N'Messagerie interne avec chat, appels vidéo et partage d''écran entre collaborateurs. Fonctionne avec Calendrier et Projet.', 1, 0, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (2, N'Salle de réunion', N'Réservation et gestion des salles de réunion de l''entreprise. Lié à Discussion et Calendrier.', 0, 0, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (3, N'Calendrier', N'Agenda centralisé synchronisé avec Outlook ou Gmail. Lié à Rendez-vous, Projet et Feuilles de temps.', 1, 0, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (4, N'Rendez-vous', N'Permet aux clients de réserver eux-mêmes un créneau en ligne selon les disponibilités définies. Lié au Calendrier et au CRM.', 0, 0, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (5, N'To-do', N'Liste de tâches personnelles avec option de partage entre collègues. Lié à Projet et Calendrier.', 1, 0, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (6, N'Connaissances', N'Base de connaissances interne de type wiki (similaire à Notion) pour documenter processus et informations.', 1, 0, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (7, N'Contact', N'Annuaire centralisé de tous les tiers : employés, clients, fournisseurs et partenaires. Base de données partagée par toutes les applications.', 1, 0, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (8, N'CRM', N'Suivi du cycle de vente : gestion des prospects, opportunités et relances commerciales. Lié à Contact, Vente et E-Mail Marketing.', 0, 0, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (9, N'Vente', N'Création et envoi de devis, gestion du catalogue produits et émission de factures. Lié au CRM, Abonnement et Comptabilité.', 0, 0, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (10, N'Tableau de bord', N'Création de dashboards personnalisés pour visualiser les données clés de l''ERP en temps réel. Lié à toutes les applications.', 1, 0, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (11, N'Abonnement', N'Gestion de la facturation récurrente (mensuelle, annuelle…). Lié à Vente et Comptabilité.', 0, 0, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (12, N'Location', N'Gestion de biens locatifs : contrats de bail, facturation, entretien et suivi des échéances. Lié à Vente et Comptabilité.', 0, 0, 9);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (13, N'AI', N'Intelligence artificielle intégrée nativement dans toutes les applications pour automatiser et assister les utilisateurs.', 1, 0, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (14, N'Comptabilité', N'Gestion comptable complète : journal, bilan, connexion bancaire et rapports financiers. Lié à Vente, Achats et Facturation.', 0, 1, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (15, N'Document', N'Gestion électronique des documents (GED) : stockage, classement et partage de fichiers. Lié à toutes les applications.', 0, 0, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (16, N'Projet', N'Gestion de projets avec suivi des tâches, jalons et ressources. Lié à Feuilles de temps, Assistance et Vente.', 0, 0, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (17, N'Feuilles de temps', N'Saisie des heures travaillées par projet ou client pour le suivi des honoraires et la facturation en régie. Lié à Projet et Comptabilité.', 0, 0, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (18, N'Service sur site', N'Planification d''interventions chez les clients avec gestion des techniciens, équipements et déplacements. Lié à Planning et Contact.', 0, 0, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (19, N'Planning', N'Gestion des plannings de travail par employé ou par équipe. Lié à Présence, Projet et Service sur site.', 0, 0, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (20, N'Assistance', N'Système de ticketing pour gérer les demandes de support clients ou internes. Lié à Live-Chat, Contact et CRM.', 0, 0, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (21, N'Site Web', N'Création et gestion d''un site web d''entreprise sans compétences techniques. Lié à e-commerce, CRM et Live-Chat.', 0, 0, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (22, N'Marketing Social', N'Gestion centralisée des publications sur les réseaux sociaux et suivi des interactions. Lié à Marketing Automation et CRM.', 0, 0, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (23, N'Marketing Automation', N'Automatisation de campagnes marketing déclenchées selon des événements ou comportements utilisateurs. Lié à CRM, E-Mail Marketing et SMS Marketing.', 0, 0, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (24, N'SMS Marketing', N'Envoi automatisé de SMS promotionnels ou de suivi client. Lié à Marketing Automation et CRM.', 0, 0, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (25, N'E-Mail Marketing', N'Création et envoi automatisé d''e-mails promotionnels ou de suivi. Lié à Marketing Automation et CRM.', 0, 0, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (26, N'Evènement', N'Organisation et gestion d''événements ponctuels (inscriptions, billets, communication). Lié à Site Web et CRM.', 0, 0, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (27, N'Sondages', N'Création de sondages en ligne ou en présentiel pour collecter des retours clients ou employés. Lié à CRM et E-Mail Marketing.', 0, 0, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (28, N'Achats', N'Gestion des commandes fournisseurs, réception des marchandises et suivi des livraisons. Lié à Inventaire et Comptabilité.', 0, 0, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (29, N'Inventaire', N'Gestion des stocks : niveaux, emplacements, mouvements et valorisation. Lié à Achats, Vente et Fabrication.', 0, 0, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (30, N'Code-barres', N'Utilisation de lecteurs de codes-barres pour identifier rapidement produits et mouvements de stock. Lié à Inventaire et Point de vente.', 0, 0, 1);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (31, N'Maintenance', N'Planification et suivi de la maintenance préventive et corrective du parc machines interne. Lié à Inventaire et Planning.', 0, 0, 4);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (32, N'Signature', N'Préparation et signature électronique de documents directement depuis l''ERP. Lié à Document et Vente.', 1, 0, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (33, N'Employés', N'Gestion des dossiers du personnel : contrats, informations personnelles et documents RH. Base des applications RH.', 0, 1, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (34, N'Paie', N'Calcul et édition des fiches de paie avec gestion des charges sociales. Lié à Employés, Présence et Comptabilité.', 0, 1, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (35, N'Evaluation', N'Gestion des entretiens d''évaluation et suivi des objectifs des employés. Lié à Employés et Gestion des compétences.', 0, 1, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (36, N'Présence', N'Pointage et suivi des heures de présence des employés. Lié à Paie, Congé et Planning.', 1, 0, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (37, N'Recrutement', N'Gestion du processus de recrutement : annonces, candidatures, entretiens. Lié à Emplois en ligne et Employés.', 0, 0, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (38, N'Recommandation', N'Permet aux employés de recommander des candidats en interne pour les postes ouverts. Lié à Recrutement.', 0, 0, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (39, N'Parc Automobile', N'Suivi des véhicules de l''entreprise : entretiens, assurances, kilométrage, achats et ventes. Lié à Employés et Dépenses.', 0, 0, 11);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (40, N'Congé', N'Gestion des demandes et soldes de congés et vacances. Lié à Présence, Planning et Employés.', 1, 0, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (41, N'Dépenses', N'Saisie et remboursement des notes de frais des employés. Lié à Comptabilité et Employés.', 0, 0, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (42, N'Live-Chat', N'Chat en direct intégré au site web pour dialoguer avec les visiteurs. Lié à Assistance et CRM.', 0, 0, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (43, N'Nettoyage des données', N'Détection et fusion des doublons et correction des anomalies dans la base de données. Lié à Contact et CRM.', 1, 0, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (44, N'Validations', N'Mise en place de workflows de validation par un responsable sur divers processus (dépenses, congés, achats…). Lié à toutes les applications.', 0, 0, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (45, N'WhatsApp', N'Intégration de WhatsApp Business dans l''ERP pour communiquer avec les clients. Lié à CRM et Assistance.', 0, 0, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (46, N'Téléphone', N'Intégration de la téléphonie VoIP pour passer et recevoir des appels depuis l''ERP. Lié à CRM et Assistance.', 0, 0, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (47, N'Tracker de Lien', N'Suivi des clics sur des liens partagés en campagne pour mesurer l''engagement commercial. Lié à E-Mail Marketing et CRM.', 0, 0, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (48, N'Restaurant', N'Gestion complète de la restauration : tables, commandes, menu et caisse. Lié à Point de vente et Inventaire.', 0, 0, 6);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (49, N'Equity', N'Gestion de la répartition du capital social, des dividendes et des droits des actionnaires. Lié à Comptabilité.', 0, 1, 18);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (50, N'Point de vente', N'Caisse enregistreuse digitale pour la vente en boutique ou au comptoir. Lié à Inventaire, Vente et Comptabilité.', 0, 0, 1);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (51, N'e-commerce', N'Boutique en ligne synchronisée en temps réel avec le stock et la comptabilité. Lié à Inventaire, Vente et Site Web.', 0, 0, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (52, N'Fabrication', N'Suivi du processus de production : ordres de fabrication, nomenclatures et contrôle qualité. Lié à Inventaire et Qualité.', 0, 0, 4);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (53, N'Studio', N'Outil de personnalisation avancée de l''ERP : modification des vues, formulaires et automatisations sans code.', 0, 0, 13);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (54, N'Database', N'Création et gestion de bases de données internes sur mesure. Lié à Studio.', 0, 0, 13);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (55, N'ESG', N'Suivi et reporting de l''empreinte écologique et des indicateurs RSE de l''entreprise. Lié à Comptabilité.', 0, 0, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (56, N'Réception', N'Gestion de l''accueil physique : enregistrement des visiteurs et gestion des badges. Lié à Employés et Calendrier.', 0, 0, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (57, N'Qualité', N'Contrôle qualité dans les processus de fabrication ou de service : alertes, non-conformités. Lié à Fabrication et Inventaire.', 0, 0, 4);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (58, N'E-Learning', N'Création et diffusion de formations en ligne pour les employés ou clients. Lié à Employés et Gestion des compétences.', 0, 0, 23);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (59, N'GCVP', N'Gestion du cycle de vie produit : de la conception à la mise en production. Lié à Fabrication et Inventaire.', 0, 0, 4);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (60, N'Réparation', N'Gestion des interventions de réparation internes avec suivi des pièces et du temps. Lié à Inventaire et Feuilles de temps.', 0, 0, 5);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (61, N'IOT', N'Connexion de capteurs et machines physiques à l''ERP via une box IoT. Lié à Fabrication et Maintenance.', 0, 0, 4);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (62, N'Gestion des compétences', N'Cartographie et suivi des compétences des employés. Lié à Employés, Recrutement et E-Learning.', 0, 0, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (63, N'Déjeuner', N'Commande et suivi des repas pour une cantine interne. Lié à Employés.', 0, 0, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (64, N'Emplois en ligne', N'Diffusion des offres d''emploi sur le site web et suivi des candidatures en ligne. Lié à Recrutement et Site Web.', 0, 0, NULL);
INSERT INTO ApplicationOdoo (Id, Nom, Description, EstEssentiel, EstAdministrative, SecteurActiviteId) VALUES (65, N'Facturation', N'Module de facturation simplifié sans les fonctionnalités bancaires de la comptabilité complète. Lié à Vente et CRM.', 0, 0, NULL);
SET IDENTITY_INSERT ApplicationOdoo OFF;

-- =====================
-- Client
-- =====================
SET IDENTITY_INSERT Client ON;
INSERT INTO Client (Id, Nom, EMail, NombreEmploye, SecteurActiviteId) VALUES (1, N'La Boutique du Village Sàrl', N'info@boutique-village.ch', 8, 1);
INSERT INTO Client (Id, Nom, EMail, NombreEmploye, SecteurActiviteId) VALUES (2, N'SuperMart Romandie SA', N'contact@supermart-romandie.ch', 420, 2);
INSERT INTO Client (Id, Nom, EMail, NombreEmploye, SecteurActiviteId) VALUES (3, N'Alpes Négoce & Distribution SA', N'info@alpes-negoce.ch', 34, 3);
INSERT INTO Client (Id, Nom, EMail, NombreEmploye, SecteurActiviteId) VALUES (4, N'Swiss Métal & Pièces AG', N'contact@swissmetalpieces.ch', 210, 4);
INSERT INTO Client (Id, Nom, EMail, NombreEmploye, SecteurActiviteId) VALUES (5, N'Menuiserie Du Coin Sàrl', N'info@menuiserie-ducoin.ch', 6, 5);
INSERT INTO Client (Id, Nom, EMail, NombreEmploye, SecteurActiviteId) VALUES (6, N'Chez Marcel Restaurant Sàrl', N'bonjour@chezmarcel.ch', 9, 6);
INSERT INTO Client (Id, Nom, EMail, NombreEmploye, SecteurActiviteId) VALUES (7, N'Hôtel Les Sapins SA', N'reception@hotel-lessapins.ch', 55, 7);
INSERT INTO Client (Id, Nom, EMail, NombreEmploye, SecteurActiviteId) VALUES (8, N'Immo Prestige Lac SA', N'info@immo-prestigelac.ch', 12, 8);
INSERT INTO Client (Id, Nom, EMail, NombreEmploye, SecteurActiviteId) VALUES (9, N'Gérance Mon Toit Sàrl', N'contact@gerance-montoit.ch', 8, 9);
INSERT INTO Client (Id, Nom, EMail, NombreEmploye, SecteurActiviteId) VALUES (10, N'Entrepôt Central Romand SA', N'ops@entrepot-central.ch', 78, 10);
INSERT INTO Client (Id, Nom, EMail, NombreEmploye, SecteurActiviteId) VALUES (11, N'Camions & Co Transport AG', N'info@camionsco.ch', 47, 11);
INSERT INTO Client (Id, Nom, EMail, NombreEmploye, SecteurActiviteId) VALUES (12, N'Info Solutions Sàrl', N'hello@infosolutions.ch', 15, 12);
INSERT INTO Client (Id, Nom, EMail, NombreEmploye, SecteurActiviteId) VALUES (13, N'Cabinet Médical du Centre', N'secretariat@cabinet-centre.ch', 5, 14);
INSERT INTO Client (Id, Nom, EMail, NombreEmploye, SecteurActiviteId) VALUES (14, N'Bâti Rapide Construction SA', N'info@bati-rapide.ch', 63, 15);
INSERT INTO Client (Id, Nom, EMail, NombreEmploye, SecteurActiviteId) VALUES (15, N'Ingénieurs Associés Sàrl', N'contact@ingenieurs-associes.ch', 29, 16);
INSERT INTO Client (Id, Nom, EMail, NombreEmploye, SecteurActiviteId) VALUES (16, N'Comptabilité Express SA', N'info@compta-express.ch', 18, 17);
INSERT INTO Client (Id, Nom, EMail, NombreEmploye, SecteurActiviteId) VALUES (17, N'Swiss Invest Holding AG', N'info@swissinvest-holding.ch', 4, 18);
INSERT INTO Client (Id, Nom, EMail, NombreEmploye, SecteurActiviteId) VALUES (18, N'Conseil & Stratégie Plus Sàrl', N'bonjour@conseil-strategie.ch', 11, 19);
INSERT INTO Client (Id, Nom, EMail, NombreEmploye, SecteurActiviteId) VALUES (19, N'MonShop En Ligne Sàrl', N'support@monshop-enligne.ch', 14, 20);
INSERT INTO Client (Id, Nom, EMail, NombreEmploye, SecteurActiviteId) VALUES (20, N'Événements Clés en Main SA', N'info@evenements-cleenmain.ch', 19, 21);
INSERT INTO Client (Id, Nom, EMail, NombreEmploye, SecteurActiviteId) VALUES (21, N'Ferme & Vigne du Plateau Sàrl', N'cave@ferme-vigne.ch', 5, 22);
INSERT INTO Client (Id, Nom, EMail, NombreEmploye, SecteurActiviteId) VALUES (22, N'École Privée Les Cèdres SA', N'info@ecole-lescedres.ch', 38, 23);
INSERT INTO Client (Id, Nom, EMail, NombreEmploye, SecteurActiviteId) VALUES (23, N'Association Aide & Solidarité', N'contact@aide-solidarite.ch', 17, 24);
SET IDENTITY_INSERT Client OFF;

-- =====================
-- Question
-- =====================
SET IDENTITY_INSERT Question ON;
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (1, N'Le client vend-il des produits physiques ?', 1, NULL, NULL, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (2, N'Le client gère-t-il un stock ?', 2, NULL, 1, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (3, N'Le client dispose-t-il d''une boutique physique ?', 3, NULL, 1, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (4, N'Le client vend-il en ligne ?', 4, NULL, 1, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (5, N'Le client propose-t-il des abonnements ou facturations récurrentes ?', 5, NULL, NULL, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (6, N'Le client facture-t-il des prestations de services ?', 6, NULL, NULL, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (7, N'Le client travaille-t-il en régie (facturation au temps passé) ?', 7, NULL, 6, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (8, N'Les techniciens interviennent-ils chez les clients sur site ?', 8, NULL, 6, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (9, N'Le client gère-t-il un portefeuille de prospects ?', 9, NULL, NULL, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (10, N'Le client réalise-t-il des campagnes marketing ?', 10, NULL, 9, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (11, N'Le client utilise-t-il les réseaux sociaux à des fins commerciales ?', 11, NULL, 10, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (12, N'Le client dispose-t-il d''un site web ?', 12, NULL, NULL, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (13, N'Le client propose-t-il un support ou SAV à ses clients ?', 13, NULL, NULL, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (14, N'Le client gère-t-il des employés ?', 14, NULL, NULL, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (15, N'Le client édite-t-il les fiches de paie en interne ?', 15, NULL, 14, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (16, N'Le client gère-t-il des plannings d''équipes ?', 16, NULL, 14, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (17, N'Les employés soumettent-ils des notes de frais ?', 17, NULL, 14, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (18, N'Le client dispose-t-il de véhicules de société ?', 18, NULL, 14, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (19, N'Le client gère-t-il des recrutements ?', 19, NULL, 14, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (20, N'Le client gère-t-il des évaluations annuelles de ses employés ?', 20, NULL, 14, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (21, N'Le client souhaite-t-il cartographier les compétences de ses employés ?', 21, NULL, 14, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (22, N'Le client dispose-t-il d''une cantine interne ?', 22, NULL, 14, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (23, N'Le client souhaite-t-il que ses employés recommandent des candidats ?', 23, NULL, 19, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (24, N'Le client nécessite-t-il une comptabilité complète avec connexion bancaire ?', 24, NULL, NULL, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (25, N'Le client gère-t-il des achats fournisseurs ?', 25, NULL, NULL, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (26, N'Le client a-t-il besoin de signatures électroniques ?', 26, NULL, NULL, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (27, N'Le client nécessite-t-il des workflows de validation ?', 27, NULL, NULL, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (28, N'Le client a-t-il plusieurs salles de réunion ?', 28, NULL, NULL, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (29, N'Le client propose-t-il des rendez-vous en ligne à ses clients ?', 29, NULL, NULL, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (30, N'Le client gère-t-il des documents administratifs ou contractuels ?', 30, NULL, NULL, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (31, N'Le client organise-t-il des événements avec inscriptions ?', 31, NULL, NULL, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (32, N'Le client réalise-t-il des sondages auprès de ses clients ou employés ?', 32, NULL, NULL, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (33, N'Le client communique-t-il avec ses clients via WhatsApp ?', 33, NULL, NULL, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (34, N'Le client utilise-t-il la téléphonie VoIP ?', 34, NULL, NULL, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (35, N'Le client suit-il les clics de ses campagnes marketing ?', 35, NULL, 10, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (36, N'Le client a-t-il des obligations de reporting RSE / ESG ?', 36, NULL, NULL, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (37, N'Le client gère-t-il un accueil physique avec visiteurs ?', 37, NULL, NULL, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (38, N'Le client gère-t-il un service en salle (tables, commandes) ?', 38, 6, NULL, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (39, N'Le client utilise-t-il une caisse enregistreuse ?', 39, 1, NULL, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (40, N'Le client utilise-t-il des lecteurs de codes-barres ?', 40, 1, 39, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (41, N'Le client utilise-t-il une caisse enregistreuse ?', 41, 2, NULL, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (42, N'Le client utilise-t-il des lecteurs de codes-barres ?', 42, 2, 41, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (43, N'Le client utilise-t-il des lecteurs de codes-barres ?', 43, 10, NULL, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (44, N'Le client gère-t-il des ordres de fabrication ?', 44, 4, NULL, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (45, N'Le client suit-il la maintenance de ses machines ?', 45, 4, 44, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (46, N'Le client connecte-t-il des machines à son ERP (IoT) ?', 46, 4, 44, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (47, N'Le client gère-t-il un contrôle qualité en production ?', 47, 4, 44, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (48, N'Le client gère-t-il le cycle de vie de ses produits ?', 48, 4, 44, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (49, N'Le client gère-t-il des contrats de bail et loyers ?', 49, 9, NULL, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (50, N'Le client gère-t-il un parc de véhicules de société ?', 50, 11, NULL, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (51, N'Le client a-t-il besoin de personnaliser l''ERP sans code ?', 51, 13, NULL, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (52, N'Le client nécessite-t-il des bases de données sur mesure ?', 52, 13, 51, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (53, N'Le client gère-t-il des participations et dividendes ?', 53, 18, NULL, NULL);
INSERT INTO Question (Id, Texte, Ordre, SecteurActiviteId, QuestionId, Reponse) VALUES (54, N'Le client propose-t-il des formations en ligne ?', 54, 23, NULL, NULL);
SET IDENTITY_INSERT Question OFF;

-- =====================
-- QuestionApplication
-- =====================
SET IDENTITY_INSERT QuestionApplication ON;
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (1, 1, 29);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (2, 1, 28);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (3, 2, 29);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (4, 3, 50);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (5, 4, 51);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (6, 4, 21);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (7, 5, 11);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (8, 6, 9);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (9, 6, 65);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (10, 7, 17);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (11, 7, 16);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (12, 8, 18);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (13, 8, 19);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (14, 9, 8);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (15, 10, 25);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (16, 10, 23);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (17, 10, 24);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (18, 11, 22);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (19, 12, 21);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (20, 12, 42);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (21, 13, 20);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (22, 13, 42);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (23, 14, 33);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (24, 14, 40);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (25, 14, 36);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (26, 15, 34);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (27, 16, 19);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (28, 17, 41);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (29, 18, 39);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (30, 19, 37);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (31, 19, 64);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (32, 20, 35);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (33, 21, 62);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (34, 22, 63);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (35, 23, 38);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (36, 24, 14);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (37, 25, 28);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (38, 26, 32);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (39, 27, 44);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (40, 28, 2);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (41, 29, 4);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (42, 30, 15);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (43, 31, 26);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (44, 32, 27);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (45, 33, 45);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (46, 34, 46);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (47, 35, 47);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (48, 36, 55);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (49, 37, 56);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (50, 38, 48);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (51, 39, 50);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (52, 40, 30);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (53, 41, 50);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (54, 42, 30);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (55, 43, 30);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (56, 44, 52);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (57, 45, 31);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (58, 46, 61);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (59, 47, 57);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (60, 48, 59);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (61, 49, 12);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (62, 50, 39);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (63, 51, 53);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (64, 52, 54);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (65, 53, 49);
INSERT INTO QuestionApplication (Id, QuestionId, ApplicationOdooId) VALUES (66, 54, 58);
SET IDENTITY_INSERT QuestionApplication OFF;
